
builder = "nixpacks"

[deploy]
startCommand = "pip install --break-system-packages -r requirements.txt && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 main:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10


PYTHON_VERSION = "3.11"
PIP_NO_CACHE_DIR = "1"
PYTHONUNBUFFERED = "1"
PIP_BREAK_SYSTEM_PACKAGES = "1"
